class LegalTexts {
  // Last updated dates for each document
  static const tosLastUpdated = 'March 20, 2024';
  static const privacyPolicyLastUpdated = 'March 15, 2024';  // Different date

  static String termsOfService({required String contactEmail}) => '''
Terms of Service for Litigence AI
Last Updated: $tosLastUpdated

1. Acceptance of These Terms
By accessing or using the Litigence AI application (the "App"), you ("you" or "User") agree to be bound by these Terms of Service (the "Terms"). If you do not agree to these Terms, you may not access or use the App.

2. Description of Service
Litigence AI is an AI-powered application designed to provide legal information and assistance to common people in India. Leveraging advanced AI models, including insights from legal documents, Litigence AI aims to:
• Provide explanations and summaries of legal concepts
• Assist users in understanding legal documents
• Offer guidance on legal processes and procedures
• Serve as an educational tool for legal literacy

3. User Conduct and Obligations
You agree to use the App responsibly and in compliance with all applicable laws and regulations. Specifically, you agree not to:
• Use the App for any illegal or unauthorized purpose
• Attempt to disrupt, damage, or gain unauthorized access to the App or its related systems
• Reverse engineer, decompile, or attempt to extract the source code of the App
• Use the output generated by the App in a manner that could be misleading or harmful
• Upload any files that contain viruses, malware, or other harmful code (once file uploading is enabled)
• Upload any content that is unlawful, defamatory, libelous, harassing, abusive, threatening, or otherwise objectionable (once file uploading is enabled)
• Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity

4. Account Registration (Future)
Currently, no account registration is required to use Litigence AI. In the future, we may implement a simple Google Authentication process to enhance user experience. Your use of Google Authentication will be subject to Google's terms and privacy policies.

5. Intellectual Property
• Our Ownership: The App, including its software, AI models, design, logos, and all content provided by Litigence AI, is owned by Litigence AI and is protected by applicable copyright, trademark, and other intellectual property laws.
• Use of AI Output: The output generated by Litigence AI is intended for informational and educational purposes only. You are granted a non-exclusive, non-transferable right to use this output for your personal, non-commercial use. You may use the output commercially, but it is your responsibility to ensure its accuracy and suitability for your specific purpose and to seek professional legal advice before acting on it.
• User Content (Future): When file uploading is enabled, any content you upload to the App will remain your property. By uploading content, you grant Litigence AI a non-exclusive, worldwide, royalty-free license to access, process, and use that content solely for the purpose of providing you with the services of the App and improving our models on an anonymized basis for non-premium users.

6. Disclaimer of Warranties and Limitation of Liability
THE APP IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, LITIGENCE AI DISCLAIMS ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT THE USE OF LITIGENCE AI IS AT YOUR SOLE RISK. LITIGENCE AI IS INTENDED FOR EDUCATIONAL AND INFORMATIONAL PURPOSES ONLY AND DOES NOT PROVIDE LEGAL ADVICE. THE OUTPUT GENERATED BY THE AI SHOULD NOT BE SUBSTITUTED FOR THE ADVICE OF A QUALIFIED LEGAL PROFESSIONAL. YOU SHOULD ALWAYS CONSULT WITH A LAWYER BEFORE MAKING ANY DECISIONS WITH LEGAL IMPLICATIONS.

LITIGENCE AI SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
• THE USE OR THE INABILITY TO USE THE APP
• ANY ERRORS OR OMISSIONS IN THE CONTENT OR OUTPUT GENERATED BY THE AI
• UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA
• STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE APP
• ANY OTHER MATTER RELATING TO THE APP

7. Termination
• Termination by You: You may cease using the App at any time. Once account registration is implemented, you will be able to request termination of your account within the App or by contacting us via email. As no data is currently collected, termination simply involves ceasing use of the App.
• Termination by Us: Litigence AI reserves the right to terminate or suspend your access to the App, with or without cause or notice, including but not limited to violations of these Terms.

8. Modifications to the Terms
We reserve the right to modify these Terms at any time. We will post any changes on this page, and the updated Terms will be effective upon posting. Your continued use of the App after the posting of revised Terms means that you accept and agree to the changes.

9. Governing Law
These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions.

10. Contact Us
If you have any questions about these Terms, please contact us at $contactEmail.
''';

  static String privacyPolicy({required String contactEmail}) => '''
Privacy Policy for Litigence AI
Last Updated: $privacyPolicyLastUpdated

1. Introduction
This Privacy Policy explains how Litigence AI ("we," "us," or "our") collects, uses, stores, and protects your personal information when you use the Litigence AI application (the "App"). We are committed to protecting your privacy and ensuring the security of your personal information.

2. Information We Collect
Currently, while the App is in its initial stages, we collect limited personal information. However, in the future, we may collect the following types of information:

• Account Information (Future): If you choose to create an account using Google Authentication, we will collect information from your Google account profile, such as your name and email address. We will only collect information necessary to create and manage your account.

• Usage Data: We may collect information about how you use the App, such as the features you use, the legal topics you explore, and the frequency and duration of your sessions. This data helps us understand how users interact with the App and improve its functionality.

• Uploaded Content (Future): When the feature is implemented, if you choose to upload files for analysis by Litigence AI, we will collect and process the content of those files.

• Device Information: We may collect information about the device you use to access the App, such as the device type, operating system, and unique device identifiers.

• Log Data: Our servers automatically record certain information when you use the App, including your IP address, browser type, referring/exit pages, and timestamps.

• Information Collected Through Cookies and Similar Technologies: We may use cookies and similar tracking technologies to collect information about your browsing activities within the App.

3. How We Use Your Information
We may use your information for the following purposes:

• To Provide and Improve the App: To operate, maintain, and improve the functionality and user experience of Litigence AI.

• Account Management (Future): To create and manage your user account if you choose to register.

• Personalization: To personalize your experience within the App.

• Communication: To communicate with you regarding updates, support, and other relevant information related to the App.

• Research and Development: To analyze usage patterns and trends to improve our AI models and develop new features. For non-premium users, this may involve using anonymized usage data and uploaded content (once available) to train and enhance our AI models. We will ensure that this data is processed in a way that does not identify you.

• To Display Advertisements (Future): If you are using the free version of the App, we may display advertisements.

• Legal Compliance: To comply with applicable laws, regulations, and legal processes.

• Security: To protect the security and integrity of the App and our users' information.

4. How We Share Your Information
We may share your information with the following categories of third parties:

• Service Providers: We may share information with third-party service providers who assist us with various aspects of our operations, such as hosting, analytics, and advertising (if applicable). These providers are contractually obligated to protect your information.

• Google (Future): If you choose to use Google Authentication, we will share information with Google for account authentication purposes, subject to Google's privacy policy.

• Legal Authorities: We may disclose your information to legal authorities if required by law or legal process.

• Business Transfers: In the event of a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred to the acquiring entity.

• Aggregated and Anonymized Data: We may share aggregated and anonymized data that does not identify you with third parties for various purposes, including research and analytics.

5. Your Rights
Depending on your location and applicable data protection laws, you may have certain rights regarding your personal information, including the right to:

• Access: Request access to the personal information we hold about you
• Correction: Request that we correct any inaccurate or incomplete personal information
• Deletion: Request the deletion of your personal information
• Object: Object to the processing of your personal information in certain circumstances
• Restriction of Processing: Request the restriction of the processing of your personal information
• Data Portability: Request to receive a copy of your personal information in a structured, commonly used, and machine-readable format
• Withdraw Consent: If we are processing your personal information based on your consent, you have the right to withdraw your consent at any time

To exercise these rights, please contact us at $contactEmail.

6. Data Security
We take reasonable measures to protect your personal information from unauthorized access, use, or disclosure. These measures include encryption, access controls, and regular security assessments. However, no method of transmission over the internet or method of electronic storage is completely secure, and we cannot guarantee absolute security.

7. Data Retention
We will retain your personal information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law.

8. Children's Privacy
Litigence AI is intended for a general audience and does not knowingly collect personal information from children under the age of 13. If you are a parent or guardian and believe that your child has provided us with personal information, please contact us, and we will take steps to delete such information.

9. Changes to this Privacy Policy
We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.

10. Contact Us
If you have any questions or concerns about this Privacy Policy or our data practices, please contact us at:

Litigence AI
$contactEmail

''';
}

